### ISSUE TITLE
Anyone use https://github.com/poise/application_javascript?

### ISSUE THREAD

**Issue by jonricaurte** [redguide/nodejs#125]
Saw that coderanger was sponsored to make chef scripts for nodejs by Chef Software and a few others. He also had a kickstarter campaign around this and was finished this fall. Was wondering if anyone could comment on the differences between that repo and this one? Seems like that repo is more updated and has more features, yet this one has more stars.

**Comment by iiro** [comment]
Hi,

I'm considering the options here. Did you made your decision @jonricaurte ?

**Comment by jonricaurte** [comment]
Yes, we are going to use application_javascript. It turns out opsworks uses it for the default chef12 cookbook for nodejs:

https://github.com/awslabs/opsworks-linux-demo-cookbook-nodejs

**Comment by tas50** [comment]
Closing this out since it's not really an issue
