### ISSUE TITLE
package install - v0.10.46?

### ISSUE THREAD

**Issue by lioramilbaum** [redguide/nodejs#137]
I am working with on AWS - ubuntu 12.04 OS

including nodejs recipe install by default very old release of nodejs.

**Comment by munusamy** [comment]
Even i did try changing the version attributes and tried even via override attributes but still I see it's trying to install older version 0.10.xx

**Comment by wridgers** [comment]
Try this:

```
override['nodejs']['repo'] = 'https://deb.nodesource.com/node_6.x'
```

**Comment by rockaBe** [comment]
@lioramilbaum Did the answer provided by @wridgers help you fix it? 
Can this be closed?

**Comment by guilhem** [comment]
maybe we have to update default version... but it's another issue :)

**Comment by lioramilbaum** [comment]
let me check it

**Comment by ericgoedtel** [comment]
This problem is going to happen for anyone who is using the release posted up on Chef supermarket. The last formal release of this project was in December of 2015. The version of node served up by that release is 0.10.

You can use an attribute override as specified for this but the default version is *already* updated in the repository--the problem is that there is no new release that reflects that change.

It would be nice if a new release could be created that is a bit more--contemporary. Alternatively, those of us using Berkshelf can add this to your Berksfile:

`cookbook 'nodejs', git: 'git://github.com/redguide/nodejs.git'`

This will pull latest master from the repo.

**Comment by lioramilbaum** [comment]
Using 3.0.0 cookbook version still deploys release v0.10.46. I was hopping that updating the cookbook will suffice. I will try to add the variable
override['nodejs']['repo'] = 'https://deb.nodesource.com/node_6.x'

**Comment by lioramilbaum** [comment]
Working when adding the variable.
Thanks

**Comment by chewi** [comment]
@lioramilbaum is right and I don't see the change that @ericgoedtel is referring to.

**Comment by chris-fa** [comment]
Is there a fix of this but for Centos 6.7?

**Comment by chewi** [comment]
Probably not, EPEL for 6 only seems to have 0.10.46.

**Comment by chris-fa** [comment]
@chewi I tried adding the nodesource repo [documented in here](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) but maybe I missed something?

`override['nodejs']['repo'] = 'https://rpm.nodesource.com/setup_6.x'`

`include_recipe 'nodejs'`

**Comment by chewi** [comment]
I didn't realise there was an RPM equivalent. That would work except that the repo recipe is hardcoded to use EPEL. You could still use the [yum_repository resource](https://docs.chef.io/resource_yum_repository.html) yourself though before calling this cookbook.

**Comment by chris-fa** [comment]
@chewi Got it, thanks man :)

**Comment by chris-fa** [comment]
@chewi I'm a little bit lost, as I can't figure which URL is the repository and which one is the GPG key.

I read the whole installation script at https://rpm.nodesource.com/setup_6.x and searched for the word `rpm` in order to find the repo, until I arrived at `https://rpm.nodesource.com/pub_6.x/` but I'm not sure this is the actual repo.

```
yum_repository 'rpm' do
    description 'RPM repo for NodeJS'
    baseurl 'https://rpm.nodesource.com/pub_6.x/'
    pgpkey ''
    action :create
end
```

Also, after setting the repo up, I can use this cookbook, `nodejs`?

**Comment by chewi** [comment]
I'm not sure but try setting this:

```ruby
override['nodejs']['packages'] = ['nodejs']
```

**Comment by Pankaj-Pippin** [comment]
Hi All

I am newbie so i am unable to understand where to put or edit as you guys having conversation , I am totally lost it :(

@chris-fa : Can you share the final script with us ? I am having same issue.

@lioramilbaum : where you added this line , in which file and where can u share that file code ?

@chewi : Could you please help me too , You are very experienced then us :) 

Thanks to All

**Comment by lioraspark** [comment]
@Pankaj-Pippin 
in my custom cookbook (the one who depends on nodejs cookbook)
attributes/default.rb:
_override['nodejs']['repo'] = 'https://deb.nodesource.com/node_6.x'_

**Comment by chris-fa** [comment]
@Pankaj-Pippin This is what I did:

```
# Adds NodeSource repo to yum
# TODO: not sure if GPG Key is correct
yum_repository 'rpm' do
    description 'RPM repo for NodeJS'
    baseurl 'https://rpm.nodesource.com/pub_6.x/el/6/x86_64/'
    gpgkey 'https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL'
    action :create
end

package 'nodejs'
```

*Note:* I'm using CentOS 6, not Ubuntu, so my repo url is different

**Comment by Pankaj-Pippin** [comment]
@lioraspark : Not work for me :( in amazon linux 

@ chris-fa 
Thank you very much Its working , I edited install.rb under recipes 

`yum_repository 'rpm' do
    description 'RPM repo for NodeJS'
    baseurl 'https://rpm.nodesource.com/pub_6.x/el/6/x86_64/'
    gpgkey 'https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL'
    action :create
end

package 'nodejs'

#include_recipe "nodejs::nodejs_from_#{node['nodejs']['install_method']}"`

I commented default method so its work file .

Now I have 1 Question for maintenaner, Myself & chris-fa  just override what you guys have written , then how chef help us here ?  This is really serious issue we cant install it on RPM based Linux , but in page its shows that it support RPM based distro and AWS, even after that issues is open .

**Comment by tas50** [comment]
So https://github.com/redguide/nodejs/pull/164 will get Debian/Ubuntu to 6.x installs by switching the repo to the correct directory. For RHEL/Amazon users I think the solution is to remove EPL and instead use the nodesource.com repo like we do on Ubuntu/Debian. It would give us a nice consistent version on all platforms and it would get RHEL up to date nodejs.

**Comment by Pankaj-Pippin** [comment]
Hi Tim,

Thanks for update , However its nearly 5 month old , and now we understand that chef is still not that mature and customizable  as we thought , so we built our own way to automate things.

Also Could you please remove the AWS icon from supported list till a fixed is deployed , Its going to save lots of time for others.

Thanks to all member for time and support :)

**Comment by tas50** [comment]
https://github.com/redguide/nodejs/pull/169 switches RHEL / Amazon to nodesource.com and adds testing on Amazon linux.
