### ISSUE TITLE
No resource or method named `ark' for `Chef::Recipe "npm_from_source"'

### ISSUE THREAD

**Issue by codemonkey84** [redguide/nodejs#138]
NoMethodError

No resource or method named ark' forChef::Recipe "npm_from_source"'

Cookbook Trace:

/var/lib/aws/opsworks/cache.stage2/cookbooks/nodejs/recipes/npm_from_source.rb:29:in `from_file'

**Comment by tas50** [comment]
You'll need to upgrade your version of Chef to at least Chef 12 since ark requires that
