### ISSUE TITLE
nodejs_from_binary recipe fails due to recent change in ark dependency

### ISSUE THREAD

**Issue by zonotope** [redguide/nodejs#150]
## Cookbook version: 
3.0.0

## Chef client version:
11.4

## Platform Details
Amazon Linux/OpsWorks

## Scenario
Recent versions of the `ark` cookbook [no longer includes `owner=` method](https://github.com/chef-cookbooks/ark/issues/181) for ark resources. This causes at least the `nodejs::nodejs_from_binary` recipe to fail with the following error:

```
================================================================================
Error executing action `install` on resource 'ark[nodejs-binary]'
================================================================================
 
 
NoMethodError
-------------
undefined method `owner=' for Chef::Resource::Ark
```

## Possible solution
The `ark` dependency [is not locked to a specific version](https://github.com/redguide/nodejs/blob/master/metadata.rb#L14) so changes upstream caused this failure. I believe this issue will be fixed by locking the `ark` dependency to version `2.1.0`.

**Comment by tas50** [comment]
Chef 11 is EOL and ark now requires Chef 12. If you want to stay on Chef 11 you'll need to manage version dependencies in your own wrapper cookbook or berkshelf config.
