### ISSUE TITLE
npm is not available when using package install with Ubuntu 16.04

### ISSUE THREAD

**Issue by teknofire** [redguide/nodejs#151]
With Ubuntu 16.04 it looks like `npm` is no longer installed with the `nodejs` package.  I had to add `npm` and `nodejs-legacy` to the package list with something the following code before I could converge

```
if node['platform_family'] == 'debian'
  if node['platform_version'].to_i == 16
    default['nodejs']['packages'] = ['nodejs', 'nodejs-legacy', 'npm']
  end
end

```

### metadata.rb

```
depends 'pm2'
depends 'nodejs'
depends 'build-essential'
```

### receipe/default.rb

```
  include_recipe 'nodejs'
  nodejs_npm 'pm2' do
    version node['pm2']['pm2_version'] if node['pm2'].attribute?('pm2_version')
  end
```

**Comment by matt-wormley** [comment]
use node_6.x repo works for me on 16.04

```
node.override['nodejs']['repo'] = 'https://deb.nodesource.com/node_6.x'
include_recipe 'nodejs'
```

**Comment by rapcal** [comment]
@matt-wormley followed your work around and everything seems good :) Thanks!

**Comment by teknofire** [comment]
Yup, that also works for me.  It looks like it was trying to install a really old version of nodejs with the default nodejs repo.

**Comment by tas50** [comment]
https://github.com/redguide/nodejs/pull/164 fixes this by using the newer repo
