### ISSUE TITLE
nodejs_npm re-installs package on every chef run

### ISSUE THREAD

**Issue by wesleung** [redguide/nodejs#153]
Adding the below seems to install that package on every chef run
```
nodejs_npm async do
  action :install
end
```

Problem looks to be in function `npm_package_installed?` which calls `url_valid?` 
This returns `list.fetch(package, {}).fetch('resolved', '').include?('url')`

`list.fetch(package, {}).fetch('resolved', '')` returns "https://registry.npmjs.org/async/-/async-2.1.4.tgz"

`list.fetch(package, {}).fetch('resolved', '').include?('url')` returns as `False` thus causing the re-install

Chef: 12.18.31
OS: Ubuntu 14

**Comment by mmarod** [comment]
I'm having the exact same issue on the exact same OS/Chef versions. I put together PR #157 to resolve the issue in what seems to be a reasonable way for my environment.

**Comment by tas50** [comment]
New release will fix this
