### ISSUE TITLE
Install node 6.x on EL via rpm.nodesource.com

### ISSUE THREAD

**Issue by ketan** [redguide/nodejs#154]
Currently nodejs is pulled from EPEL, and I was wondering if it'd be cool to pull from rpm.nodesource.com instead of EPEL.

I'm happy to submit a PR for this.

**Comment by tas50** [comment]
I think we should probably switch away from EPEL and instead use the nodesource.com repos which we're currently using on debian/ubuntu. It would give modern versions on RHEL 6/Amazon and would line all the versions up across platforms.

**Comment by tas50** [comment]
https://github.com/redguide/nodejs/pull/169 resolves this
