### ISSUE TITLE
Amazon Linux - stop installing nodejs from epel?

### ISSUE THREAD

**Issue by eric-tucker** [redguide/nodejs#167]
Any plans to do this? 

http://stackoverflow.com/questions/27350634/how-to-yum-install-node-js-on-amazon-linux/35165401#35165401

Why aren't we using the nodejs repos to install nodejs on Amazon Linux?  Epel 6 is massively outdated and won't be getting updated.

**Comment by tas50** [comment]
https://github.com/redguide/nodejs/pull/169 resolves this
