### ISSUE TITLE
Install on centos 7.3 fails due to package removed from yum-epel

### ISSUE THREAD

**Issue by daften** [redguide/nodejs#185]
### Cookbook version
Irrelevant

### Chef-client version
Irrelevant

### Platform Details
Centos 7.3 bento box vagrant

### Scenario:
Install nodejs

### Steps to Reproduce:
Just issue the nodejs recipe on a centos 7.3 (blank system)

### Expected Result:
Nodejs installed

### Actual Result:
An error due to a missing dependency. A dependency for nodejs was removed from yum-epel because it is being put in the main yum repo's starting with centos 7.4
This gives a broken install for older blank centos systems.

I fixed it with this code ATM
```
# Temporary to fix https://bugzilla.redhat.com/show_bug.cgi?id=1481470
# For nodejs
package "yum-utils"
execute "Install CentOS CR" do
  command "yum-config-manager --enable cr"
  creates "/etc/yum.repos.d/CentOS-CR.repo"
end
```

**Comment by tas50** [comment]
I appreciate this note, but unfortunately there's nothing we can do here. Redhat really screwed this up and we're going to have to wait for the fallout to settle once CentOS 7.4 goes out. Anyone reading this can certainly pull in the continuous release repo above, but that's not something we'd want to enable for all users.

**Comment by daften** [comment]
How about adding it in documentation, in the README for other users? Is that an option :)
