### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by inopinatus** [redguide/nodejs#203]
Can I request a release bump to the supermarket? Prefer that to using a git source.

**Comment by iennae** [comment]
I'm checking to see whether I can get privs on Supermarket. Thanks for this issue.

**Comment by edgarasg** [comment]
Any news?

**Comment by iennae** [comment]
Apologies, I did get the privs but it took me a while and missed coming back to this. It looks like it's been updated on supermarket now though!
