### ISSUE TITLE
Suse didn't work

### ISSUE THREAD

**Issue by gimler** [redguide/nodejs#36]
I get since yesterday a error message.

Env:
- Suse 11 SP3

Error:
  ERROR: There are no nodejs packages for this platform; please use the source or binary method to install node

metadata.rb

```
depends "nodejs"
```

Cheffile

```
cookbook 'nodejs', '~>2.0.0'
```

```
cookbook 'nodejs'
```

I try several ways every time same error:

```
include_recipe "nodejs::nodejs_from_source"
```

```
include_recipe "nodejs::nodejs_from_binary"
```

i also try to set the install_method in my attributes/default.rb

```
default['nodejs']['install_method'] = 'binary'
```

```
default['nodejs']['install_method'] = 'source'
```

Suse has no package for nodejs.

**Comment by tas50** [comment]
https://github.com/redguide/nodejs/pull/164 provides the initial suse support.
