### ISSUE TITLE
Change the user that nodejs_npm runs under?

### ISSUE THREAD

**Issue by mansona** [redguide/nodejs#37]
We're installing pm2 using nodejs_npm and it's complaining about installing it as a root user

```
             ##### PM2 INSTALLATION
             #
             #
             # As you run PM2 as root, to update PM2 automatically
             # you must add the --unsafe-perm flag.
             #
             #       $  npm install pm2 -g --unsafe-perm
             #
             # Else run the installation as a non root user
```

is there a way to change the user that is actually running the npm install using this lwrp?

**Comment by BarthV** [comment]
I'll try to find whats wrong here.
But user / group attributes should do the work ...
https://github.com/redguide/nodejs/blob/master/providers/npm.rb#L9-L11
