### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tas50** [redguide/nodejs#48]
Any chance the changelog can get updated for the current 2.2 release up on the community site?

Thanks,
Tim

**Comment by triccardi-systran** [comment]
It would be most useful, as it's displayed directly on the Chef Supermarket.

**Comment by guilhem** [comment]
@triccardi-systran humm I wasn't aware of this feature ^^
We really have to complete this, you're right... Next version must have this as mandatory!
My bad for previous release without it...

**Comment by triccardi-systran** [comment]
Thanks @guilhem !
