### ISSUE TITLE
Broken nodejs::npm_from_source in 2.3

### ISSUE THREAD

**Issue by pelletiermaxime** [redguide/nodejs#67]
Hi, juste updated to 2.3 and the install of npm from source is broken when it does the make install:
```
node: command not found
```

I fixed it for now by installing 'nodejs-legacy'.

I don't know if it's worth it's own bug report, but 'ark' is idempotent on it's source, so because the source were already downloaded, running chef didn't reinstall properly npm. Maybe you could add something like this ? :
```
creates '/usr/local/bin/npm'
```

Thanks.

**Comment by guilhem** [comment]
Hi @pelletiermaxime, you can still pin cookbook to '~> 2.2.0' :)

I will check this problem

**Comment by BarthV** [comment]
Hi @pelletiermaxime & thanks for this report.

Sadly, I'm not able to reproduce your ```make install``` error.
I'm building node from source with bundled kitchen-test, and it's fully working either for node 0.10.26 and 0.12.2.

Are you using a custom wrapper around nodejs cookbook ?
Can you give us more details about this error and your recipes ?

**Comment by pelletiermaxime** [comment]
I'm testing with a kitchen-docker setup on a Debian Wheezy image. My cookbook is simply this :

```
include_recipe 'build-essential'
include_recipe 'nodejs::npm_from_source'
```

**Comment by BarthV** [comment]
@guilhem :

```bash
root@npm-source-ubuntu-1204:/usr/local/npm-2.7.4# make install
node cli.js install -g -f 
bash: node: command not found
make: *** [install] Error 127
```

**Comment by pelletiermaxime** [comment]
Thanks!
