### ISSUE TITLE
Cannot install sailsjs on Vagrant with node 0.12.2 and npm 2.7.4

### ISSUE THREAD

**Issue by endorama** [redguide/nodejs#78]
When trying to install sailsjs on a vagrant machine provisioned with chef-solo the process fails with this exception:

```
Mixlib::ShellOut::ShellCommandFailed - nodejs_npm[sails] (nodejs::npm_packages line 2) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[install NPM package sails] (/tmp/vagrant-chef/8dd057f72a2ebfa476b47e58636968fc/cookbooks/nodejs/providers/npm.rb line 6) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
```

node -v: 0.12.2
npm -v: 2.7.4

Installing from command line ( ssh-ed in the vagrant machine ) run successfully:
```
$ sudo npm install -g sails
...
$ echo $?
0
```

node.json
```
"run_list": [
    ...
    "nodejs",
    ...
  ],
  "nodejs": {
    "install_method": "binary",
    "version": "0.12.2",
    "repo": "https://deb.nodesource.com/node_0.12",
    "binary": {
      "checksum": {
        "linux_x64": "4e1578efc2a2cc67651413a05ccc4c5d43f6b4329c599901c556f24d93cd0508"
      }
    },
    "npm_packages": [
      { "name": "sails" },
      { "name": "grunt-cli" },
      { "name": "pm2" }
    ]
  }
}
```

Any hint on how to solve this? Same node.json with node 0.10.38 works fine.

**Comment by BarthV** [comment]
I need to check it further, but it looks like https://github.com/balderdashy/sails/issues/2826.

Please login to the current machine you are trying to converge, and run a simple ```npm install sails``` to check if your error is the upper one.

**Comment by endorama** [comment]
Installing sails from command line works. Both global installation ( `npm install -g sails` ) and local installation ( `npm install sails` ) are working as expected. I can provide the full log if needed.

**Comment by BarthV** [comment]
```
# npm -v
2.7.4
# node -v
v0.12.2
```

`npm install sails` is 100% ok.

Please reopen if necessary.
