### ISSUE TITLE
Setting the nodejs engine to iojs and install_method to 'source' does not change the prefix_url

### ISSUE THREAD

**Issue by kembs** [redguide/nodejs#85]
Hello,

I'm new to chef.. and I don't open many bugs bare with me....

my /cookbook/attributes/default.rb
default['nodejs']['engine'] = 'iojs'
default['nodejs']['version'] = '2.2.1'
default['nodejs']['source'] = { :checksum => '55e79cc4f4cde41f03c1e204d2af5ee4b6e4edcf14defc82e518436e939195fa' }
default['nodejs']['install_method'] = 'source'

Keeps creating this chef error:
```  ================================================================================
  Error executing action `create` on resource 'remote_file[/var/chef/cache/iojs-source-2.2.1.tar.gz]'
  ================================================================================

Net::HTTPServerException
  ------------------------
  404 "Not Found"
  
  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/ark/providers/default.rb
  
  279:   remote_file new_resource.release_file do
  280:     Chef::Log.debug('DEBUG: new_resource.release_file')
  281:     source new_resource.url
  282:     checksum new_resource.checksum if new_resource.checksum
  283:     action :create
  284:     notifies :run, "execute[unpack #{new_resource.release_file}]"
  285:   end
  286: 
  
  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/ark/providers/default.rb:279:in `block in class_from_file'
  
  remote_file("/var/chef/cache/iojs-source-2.2.1.tar.gz") do
    provider Chef::Provider::RemoteFile
    action [:create]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    path "/var/chef/cache/iojs-source-2.2.1.tar.gz"
    backup 5
    atomic_update true
    source ["http://nodejs.org/dist/v2.2.1/iojs-v2.2.1.tar.gz"]
    use_etag true
    use_last_modified true
    declared_type :remote_file
    cookbook_name "nodejs"
    checksum "55e79cc4f4cde41f03c1e204d2af5ee4b6e4edcf14defc82e518436e939195fa"
  end
  ``` 

Notice the source goes and fetch from the nodejs and not iojs server

If I override the prefix_url in my cookbook before load the include_recipe of "nodejs" with
node.override['nodejs']['prefix_url'] = 'http://iojs.org/dist/'

Then it works fine.

So I'm wondering if the
https://github.com/redguide/nodejs/blob/8fde9f58856c1243551ab9c2492c96bb420698ed/attributes/default.rb#L31

Works as intended?

Thanks,
Kyle

**Comment by BarthV** [comment]
I can reproduce this error.
Wondering why this attributes are not working as intended :
```ruby
if node['nodejs']['engine'] == 'iojs'
  default['nodejs']['prefix_url'] = 'http://iojs.org/dist/'
else
  default['nodejs']['prefix_url'] = 'http://nodejs.org/dist/'
end
```

**Comment by BarthV** [comment]
ok ...
It was an obvious mistake from us :space_invader: : 
If you write this : 
```ruby
default['nodejs']['engine'] = 'node' # or iojs
if node['nodejs']['engine'] == 'iojs'
[...]
end
```
IF test always return false ;-) ... that's why ```prefix_url``` always point to nodejs website.

**Comment by BarthV** [comment]
But it's not enough one way or another nodejs cookbook wipes all node['nodejs'] hash or it makes impossible to override engine value... I'm trying to found the root cause
