### ISSUE TITLE
mburns maintainer request

### ISSUE THREAD

**Issue by mburns** [redguide/nodejs#87]
Hi, I'd like to request becoming a maintainer of this cookbook to share the maintenance burden and help lower the response time for Issues and reviews on Pull Requests that come in from the community.

Is there a process for this in place(@guilhem)?

Cheers!

**Comment by BarthV** [comment]
![spider-man-2-uncle-ben-cliff-robertson-great-power-quote](https://cloud.githubusercontent.com/assets/1901955/8128894/df36e680-1103-11e5-8835-60135538e9a9.png)

* Don't push into master (unless trivial and very simple hotfix)
* Use develop branch wherever it exists
* Ask for 1~2 :+1: before merge
* Use the force & appeal to common sense

Welcome !

**Comment by mburns** [comment]
![chef's honor](http://upload.wikimedia.org/wikipedia/en/e/e7/The_Swedish_Chef.jpg)

> * Don't push into master (unless trivial and very simple hotfix)
> * Use develop branch wherever it exists
> * Ask for 1~2 :+1: before merge
> * Use the force & appeal to common sense
> * Aim to top quality cookbook !

I promise. :smile:
