### ISSUE TITLE
Is node installed as root

### ISSUE THREAD

**Issue by ballerabdude** [redguide/nodejs#91]
I'd rather install node under a user instead of root. Im looking at the code but I can't seem to see if the cookbook is installing node as a root user. If so I can create a pull request to install node/npm as a user.

**Comment by guilhem** [comment]
Yes node or iojs is installed as root.... like any other program on a unix system. Up to you to run it as any user you want (hopefully not root ;) )

**Comment by ballerabdude** [comment]
I'm an idiot. The life of a developer trying to do sys admin stuff. I was trying to use nvm but I guess just installing node would be the right way of doing this. How can I run node as a user? When I try to install a npm package globally it wants it in root. What am I doing wrong? If its in the documentation just let me know because I can't seem to find it. If I have to run a gulp task would I have to run it with sudo? Thanks again for your help.

**Comment by ballerabdude** [comment]
Checkout this article. http://tnovelli.net/blog/blog.2011-08-27.node-npm-user-install.html

**Comment by ballerabdude** [comment]
I figured it out.
